"""initial

Revision ID: 4283c075de99
Revises: 
Create Date: 2025-12-24 16:36:20.767102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4283c075de99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_health_trainee_date'), table_name='health')
    op.create_index('idx_health_trainee_date', 'health', ['trainee_id', sa.literal_column('todays_date DESC')], unique=False)
    op.drop_constraint(op.f('health_ibfk_1'), 'health', type_='foreignkey')
    op.create_foreign_key(None, 'health', 'trainees', ['trainee_id'], ['id'])
    op.drop_index(op.f('idx_name'), table_name='trainees')
    op.create_index(op.f('ix_trainees_name'), 'trainees', ['name'], unique=False)
    op.drop_index(op.f('email'), table_name='users')
    op.drop_index(op.f('idx_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_trainees_name'), table_name='trainees')
    op.create_index(op.f('idx_name'), 'trainees', ['name'], unique=False)
    op.drop_constraint(None, 'health', type_='foreignkey')
    op.create_foreign_key(op.f('health_ibfk_1'), 'health', 'trainees', ['trainee_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_health_trainee_date', table_name='health')
    op.create_index(op.f('idx_health_trainee_date'), 'health', ['trainee_id', 'todays_date'], unique=True)
    # ### end Alembic commands ###
