"""add timezone to workout date

Revision ID: 49ce088ec1fe
Revises: c2c66fd4a5b0
Create Date: 2026-02-05 17:56:54.708274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ce088ec1fe'
down_revision: Union[str, Sequence[str], None] = 'c2c66fd4a5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
