"""remove_next_training_column

Revision ID: 8be8bbfc53f8
Revises: 4283c075de99
Create Date: 2026-02-05 13:31:03.309606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8be8bbfc53f8'
down_revision: Union[str, Sequence[str], None] = '4283c075de99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainees', 'next_training')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainees', sa.Column('next_training', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
