"""add_cascade_to_health

Revision ID: c2c66fd4a5b0
Revises: 8be8bbfc53f8
Create Date: 2026-02-05 16:43:49.141903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c66fd4a5b0'
down_revision: Union[str, Sequence[str], None] = '8be8bbfc53f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('health_ibfk_1'), 'health', type_='foreignkey')
    op.create_foreign_key(None, 'health', 'trainees', ['trainee_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health', type_='foreignkey')
    op.create_foreign_key(op.f('health_ibfk_1'), 'health', 'trainees', ['trainee_id'], ['id'])
    # ### end Alembic commands ###
